disabled_rules:
  - opening_brace
  - empty_enum_arguments
  - control_statement
  - inclusive_language
  - multiple_closures_with_trailing_closure
nesting:
  type_level: 3
type_name:
  max_length: 50
large_tuple:
  warning: 3
line_length: 150
function_body_length:
  warning: 80
  error: 90
file_length:
  warning: 400
  error: 500
type_body_length:
  warning: 250
  error: 300
cyclomatic_complexity:
  ignores_case_statements: true
function_parameter_count: 8
identifier_name:
  validates_start_with_lowercase: true
  min_length:
    warning: 1
    error: 2
  excluded:
    - N
    - x
    - y
    - z
    - i
    - n
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Resources/

custom_rules:
  smiley_face:
    name: "Smiley Face"
    regex: '( :\))'
    match_kinds:
      - comment
      - string
    message: "A closing parenthesis smiley :) creates a half-hearted smile, and thus is not preferred. Use :]"
    severity: warning
